import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "https://esm.sh/resend@2.0.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface SendDDReportRequest {
  companyName: string;
  recipientEmails: string[];
  ccEmails?: string[];
  reportHtml: string;
  attachment?: {
    name: string;
    content: string;
    type: string;
  };
}

serve(async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const resendApiKey = Deno.env.get("RESEND_API_KEY");
    
    if (!resendApiKey) {
      console.log("RESEND_API_KEY not configured - email will not be sent");
      return new Response(
        JSON.stringify({ 
          success: false, 
          error: "Email service not configured. Please add RESEND_API_KEY in Settings → Integrations." 
        }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const { companyName, recipientEmails, ccEmails, reportHtml, attachment }: SendDDReportRequest = await req.json();

    if (!recipientEmails || recipientEmails.length === 0) {
      return new Response(
        JSON.stringify({ error: "At least one recipient email is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (!companyName) {
      return new Response(
        JSON.stringify({ error: "Company name is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`Sending DD report for ${companyName} to ${recipientEmails.join(", ")}`);

    const resend = new Resend(resendApiKey);

    const emailBody = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>Deep Due Diligence Report - ${companyName}</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto; color: #1a1a1a; }
            h1 { color: #0f172a; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }
            h2 { color: #1e40af; margin-top: 24px; }
            .header { background: linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%); color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
            .header h1 { border: none; color: white; margin: 0; }
            .section { margin-bottom: 24px; padding: 16px; background: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0; }
            .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 500; }
            .badge-green { background: #dcfce7; color: #166534; }
            .badge-yellow { background: #fef9c3; color: #854d0e; }
            .badge-red { background: #fee2e2; color: #991b1b; }
            .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b; text-align: center; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Deep Due Diligence Report</h1>
            <p style="margin: 8px 0 0 0; opacity: 0.9;">Analysis for ${companyName}</p>
          </div>
          
          ${reportHtml}
          
          <div class="footer">
            <p>Generated by AI VC Due Diligence Copilot • ${new Date().toLocaleDateString()}</p>
            <p>This report is for informational purposes only and does not constitute investment advice.</p>
          </div>
        </body>
      </html>
    `;

    const attachments = attachment ? [{
      filename: attachment.name,
      content: attachment.content,
      type: attachment.type,
    }] : [];

    const emailResponse = await resend.emails.send({
      from: "DD Report <onboarding@resend.dev>",
      to: recipientEmails,
      cc: ccEmails && ccEmails.length > 0 ? ccEmails : undefined,
      subject: `Deep Due Diligence Report - ${companyName}`,
      html: emailBody,
      attachments: attachments.length > 0 ? attachments : undefined,
    });

    console.log("Email sent successfully:", emailResponse);

    return new Response(
      JSON.stringify({ 
        success: true, 
        message: `DD report sent to ${recipientEmails.join(", ")}`,
        data: emailResponse
      }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (error: unknown) {
    console.error("Error sending DD report:", error);
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
